### ISSUE TITLE
Testing-related questions

### ISSUE THREAD

**Issue by sxpro** [Omnidirectional-video-group/360VISTA#1]
1. GPU model and VRAM. 
2. . What is the input resolution for computation? Alternatively, is it the average time taken to process the test set? 
3.  There seems to be an issue with the testing code; it requires the inclusion of torch.cuda.synchronize() to ensure accurate timing. Ref: https://github.com/Zheng222/IMDN/blob/master/test_IMDN.py#L73C1-L73C2

**Comment by Ahmed-Telili** [comment]
Hello @sxpro,
Thank you for bringing these points to attention. I will try to answer each in turn: 
1. The final submitted model will be evaluated on a desktop computer configured with an Intel® Xeon 8280 CPU @ 2.70GHz × 56, 128GB RAM, and an NVIDIA RTX 6000 Ada graphics card with 48GB of VRAM. 
2.  We use 2K resolution as input to compute inference time. The average is calculated over the 2K videos in the test set (around 10 videos).
3. We included torch.cuda.synchronize() to ensure accurate timing in our code. Thanks for mentioning this.
